# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Ruby

on:
  push:
    branches: [ jekyllbuild ]
  pull_request:
    branches: [ jekyllbuild ]

jobs:
  manual_build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5.1'
          bundler: 'Gemfile.lock'
          bundler-cache: true
          cache-version: 1
      - name: Install dependencies
        run: bundle install
      - name: Check content
        run: pwd && ls -al
      - name: Build the website
        run: bundle exec jekyll build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site/
          force_orphan: true

      - name: Check site
        run: ls -al _site/*

